version: '3.8'

services:
  web:
    build: .
    container_name: webide-app
    command: npm run dev
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: webide
      DB_USER: root
      DB_PASSWORD: password
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/client/node_modules
      - ./user_projects:/app/user_projects
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: webide-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webide
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data: